### PR TITLE
Typo: bath -> bash

### PR DESCRIPTION
**Pull request by hartzell**

### CODE REVIEW

**Comment by hashar** [comment]
@gboissinot @ndeloof that is an easy one :-]

**Comment by IantoMcGuckin** [comment]
Hi, could anyone please send me a built .hpi for custom install to Jenkins?  I really need this plugin, but can't build it?  And can't find it for download anywhere

**Comment by hashar** [comment]
@IantoMcGuckin fill a new issue?  Your request is unrelated to this pull request.

**Comment by dheid** [comment]
Sorry, but the correct word is batch and not bash

**Comment by dheid** [comment]
I fixed the typo directly

**Comment by hashar** [comment]
Nice! I haven't caught the bash/batch issue; well done @dheid

**Pull request closed without merging**
